#!/bin/bash

python3 couttofmt.py --update --file /home/sean/oxen-core/tests/crypto/crypto.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/crypto/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/functional_tests/transactions_flow_test.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/functional_tests/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/functional_tests/transactions_generation_from_blockchain.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/load_from_binary.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/levin.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/signature.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/block.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/fuzzer.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/base58.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/load_from_json.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/cold-transaction.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/bulletproof.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/cold-outputs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/transaction.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/block_weight/block_weight.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/node_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/parse_amount.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/bulletproofs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/multiexp.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/logging.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/epee_levin_protocol_handler_async.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/crypto.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/block_queue.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/net.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/wipeable_string.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/checkpoints.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/epee_utils.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/median.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/keccak.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/account.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/epee_boosted_tcp_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/ringct.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/service_nodes.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/ringdb.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/test_peerlist.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/multisig.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/long_term_block_weight.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/levin.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/service_nodes_swarm.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/serialization.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/rolling_median.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/lmdb.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/unbound.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/blockchain_db.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/apply_permutation.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/parse_address.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/uri.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/sha256.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/string_util.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/test_notifier.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/output_distribution.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/memwipe.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/notify.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/threadpool.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/expect.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/device.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/chacha.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/base58.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/random.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/output_selection.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/mul_div.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/block_reward.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/subaddress.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/mlocker.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/hashchain.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/sqlite.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/pruning.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/test_tx_utils.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/hmac_keccak.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/vercmp.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/get_xtype_from_string.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/oxen_name_system.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/varint.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/mnemonics.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/difficulty.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/test_protocol_pack.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/command_line.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/aligned.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/hash-target.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_proxy/core_proxy.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/daemon.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/trezor_tests.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/tools.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/daemon_tests/transfers.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/bulletproofs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/ring_signature_1.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chaingen001.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chaingen.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chain_split_1.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/multisig.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/rct.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/block_validation.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/oxen_tests.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chain_switch_1.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/wallet_tools.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/double_spend.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/transaction_tests.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/v2_tests.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/tx_validation.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/block_reward.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chaingen_main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/integer_overflow.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/hash/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/libwallet_api_tests/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/net_load_tests/clt.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/net_load_tests/srv.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/difficulty/difficulty.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/crypto/crypto-tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/functional_tests/transactions_flow_test.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/functional_tests/transactions_generation_from_blockchain.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/fuzz/fuzzer.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/random_path.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/testdb.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/unit_tests/unit_tests_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/blockchain_sqlite_test.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/io.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_proxy/core_proxy.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/daemon.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/trezor_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/trezor/tools.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/v2_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/bulletproofs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/multisig.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chaingen_tests_list.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chain_switch_1.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/tx_validation.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/rct.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/block_validation.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chain_split_1.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/transaction_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/integer_overflow.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/ring_signature_1.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/wallet_tools.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/chaingen.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/double_spend.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/oxen_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/core_tests/block_reward.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/net_load_tests/net_load_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/subaddress_expand.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/performance_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/generate_keypair.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/sc_check.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/generate_key_derivation.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/multi_tx_test_base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/ge_tobytes.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/cn_fast_hash.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/derive_secret_key.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/derive_public_key.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/cn_slow_hash.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/check_tx_signature.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/sig_clsag.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/ge_frombytes_vartime.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/multiexp.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/equality.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/bulletproof.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/single_tx_test_base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/crypto_ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/construct_tx.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/timings.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/signature.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/generate_key_image_helper.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/sc_reduce32.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/performance_tests.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/generate_key_image.h
python3 couttofmt.py --update --file /home/sean/oxen-core/tests/performance_tests/is_out_to_acc.h
