#!/bin/bash

python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/cryptonote_protocol_handler.inl
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_node.inl
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/cryptonote_core.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/hash.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/oaes_lib.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto-ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/initializer.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/skein.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/chacha.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/c_threads.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/groestl.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/oaes_config.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/variant2_int_sqrt.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/groestl_tables.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/generic-ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/crypto-ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/crypto_sign.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge_sub.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/sqrtm1.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/crypto-ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/base2.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/fe.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/d2.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/api.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge_add.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge_msub.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge_madd.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/ge_p2_dbl.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/pow22523.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/pow225521.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/d.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10CommentedCombined/sc.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/crypto_int32.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/api.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge_sub.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/sqrtm1.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/base2.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/fe.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/d2.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/api.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge_add.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge_msub.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge_madd.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/ge_p2_dbl.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/pow22523.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/pow225521.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/d.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/ref10/sc.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/crypto_uint32.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/crypto_verify_32.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto_ops_builder/sha512.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/random.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/blake256.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/jh.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/hash-ops.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/hmac-keccak.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/skein_port.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/keccak.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/util.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/meta.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/spawn.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/fs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/common_fwd.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/perf_timer.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/string_util.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/median.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/error.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/command_line.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/varint.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/file.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/pruning.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/boost_serialization_helper.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/oxen.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/base58.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/rules.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/lock.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/hex.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/threadpool.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/random.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/notify.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/periodic_task.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/unordered_containers_boost_serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/scoped_message_writer.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/json_util.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/expect.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/sha256sum.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/apply_permutation.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/combinator.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/signal_handler.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/i18n.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/aligned.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/password.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_peerlist.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_node.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_node_common.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/p2p_protocol_defs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_peerlist_boost_serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/cryptonote_protocol_defs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/quorumnet_conn_matrix.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/block_queue.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/quorumnet.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/cryptonote_protocol_handler.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/levin_notify.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/cryptonote_protocol_handler_common.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/difficulty.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_format_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_basic_impl.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/miner.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_basic.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_boost_serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/txtypes.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/subaddress_index.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/verification_context.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/account_boost_serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/hardfork.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/tx_extra.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/connection_context.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/account.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/platform/msc/stdbool.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/platform/msc/sys/param.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/platform/msc/alloca.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/platform/msc/inline_c.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/platform/mingw/alloca.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/cryptonote_tx_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_swarm.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/blockchain.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_blink.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_rules.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/pulse.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/oxen_name_system.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_quorum_cop.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_voting.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/uptime_proof.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_sanity_check.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_list.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/cryptonote_core.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_pool.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/i2p_address.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/error.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/fwd.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/socks.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/dandelionpp.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/tor_address.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/parse.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/unordered_set.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/vector.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/crypto.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/deque.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/binary_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/json_utils.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/binary_archive.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/container.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/list.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/set.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/variant.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/pair.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/json_archive.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/boost_std_optional.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/string.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/serialization/boost_std_variant.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/logging/dev_sink.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/logging/oxen_logger.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blocks/blocks.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/rpc_command_executor.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/command_server.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/daemon.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/command_line_args.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/command_parser_executor.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/rpc_args.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_server_base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/core_rpc_server_commands_defs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/core_rpc_server.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/core_rpc_server_error_codes.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_client.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/lmq_server.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/bootstrap_daemon.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_server.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/bulletproofs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctSigs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctTypes.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctCryptoOps.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctOps.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/multiexp.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/version.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/oxen_economy.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/singleton.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/english_old.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/spanish.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/language_base.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/dutch.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/russian.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/lojban.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/electrum-words.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/chinese_simplified.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/german.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/english.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/french.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/italian.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/esperanto.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/japanese.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/portuguese.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/bootstrap_serialization.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_objects.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blocksdat_file.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/bootstrap_file.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_utilities.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/tx_construction_data.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/transfer_details.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/message_store.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_rpc_server.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet2.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/transfer_view.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_errors.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/multisig_sig.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/multisig_info.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/pending_tx.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_light_rpc.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/transfer_destination.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_rpc_server_error_codes.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/message_transporter.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_args.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/ringdb.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_rpc_server_commands_defs.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/node_rpc_proxy.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/tx_sets.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/unsigned_transaction.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/transaction_history.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/pending_transaction.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/transaction_info.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/wallet_manager.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/subaddress_account.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/wallet.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/wallet2_api.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/subaddress.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/stake_unlock_result.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/address_book.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/common_defines.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/checkpoints/checkpoints.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/sqlite/db_sqlite.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/locked_txn.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/testdb.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/blockchain_db.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/lmdb/db_lmdb.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/multisig/multisig.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_config.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemonizer/daemonizer.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemonizer/windows_service.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemonizer/windows_service_runner.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/simplewallet/simplewallet.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/util.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/table.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/transaction.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/database.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/error.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/key_stream.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/value_stream.h
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/cn_heavy_hash_hard_intel.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/crypto.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/cn_heavy_hash_hard_arm.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/crypto/cn_heavy_hash_soft.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/util.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/combinator.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/perf_timer.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/oxen.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/i18n.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/string_util.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/sha256sum.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/notify.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/threadpool.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/expect.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/password.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/base58.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/random.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/scoped_message_writer.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/rules.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/error.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/pruning.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/file.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/compat/glibc_compat.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/spawn.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/common/command_line.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_node.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/p2p/net_peerlist.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/core_protocol_instantiation.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/block_queue.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/cryptonote_protocol_defs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/levin_notify.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/quorumnet.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_protocol/p2p_net_node_instantiation.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_basic_impl.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_format_utils.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/account.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/tx_extra.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/cryptonote_basic.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/miner.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/hardfork.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_basic/difficulty.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_quorum_cop.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_list.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/pulse.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_pool.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/blockchain.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_rules.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_voting.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_blink.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/uptime_proof.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/service_node_swarm.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/tx_sanity_check.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/oxen_name_system.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/cryptonote_core/cryptonote_tx_utils.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/i2p_address.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/dandelionpp.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/epee_network_address_hack.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/error.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/socks.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/tor_address.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/net/parse.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/debug_utilities/object_sizes.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/debug_utilities/cn_deserialize.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/logging/oxen_logger.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/daemon.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/rpc_command_executor.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/main.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/command_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemon/command_parser_executor.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_server_base.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/bootstrap_daemon.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/lmq_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/core_rpc_server_commands_defs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/http_client.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/core_rpc_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/rpc/rpc_args.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctSigs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctOps.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/ringct/rctTypes.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/io_ledger_tcp.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/device_default.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/io_hid.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/device_ledger.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/device.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device/log.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/mnemonics/electrum-words.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/device_trezor.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/trezor/messages_map.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/trezor/protocol.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/trezor/transport.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/trezor/debug_link.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/device_trezor/device_trezor_base.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/bootstrap_file.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_import.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/sn_key_tool.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_prune.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_ancestry.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_blackball.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_depth.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_export.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_prune_known_spent_data.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_usage.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blockchain_stats.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_utilities/blocksdat_file.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet2.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_rpc_server.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/node_rpc_proxy.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/message_store.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/ringdb.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_rpc_server_commands_defs.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/wallet_args.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/message_transporter.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/transfer_view.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/stake_unlock_result.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/wallet_manager.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/wallet.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/unsigned_transaction.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/utils.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/subaddress.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/address_book.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/transaction_history.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/transaction_info.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/subaddress_account.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/wallet/api/pending_transaction.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/gen_multisig/gen_multisig.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/checkpoints/checkpoints.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/blockchain_db.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/sqlite/db_sqlite.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/blockchain_db/lmdb/db_lmdb.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/sqlitedb/database.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/multisig/multisig.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/daemonizer/windows_service.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/simplewallet/simplewallet.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/database.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/value_stream.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/error.cpp
python3 couttofmt.py --update --file /home/sean/oxen-core/src/lmdb/table.cpp
